version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    allow:
      - dependency-name: "*discord*"
      - dependency-name: "minecraft-server-util"
      - dependency-name: "openai"

